app1/urls.py
from django.urls import path
from app1.views import *
app_name='jasu'

urlpatterns=[ 
    path('first/',first,name='first'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='jasu1'

urlpatterns=[ 
    path('second/',second,name='second'),
]

project10/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
 
def first(request):
    return render(request,'first.html')

app2/views.py
from django.shortcuts import render

# Create your views here.

def second(request):
    return render(request,'second.html')

templates/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>this is html page</h1>
    <a href="{% url 'jasu1:second' %}">go to second html page</a>
</body>
</html>

templates/second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>this is second html page</h1>
    <a href="{% url 'jasu:first'%}">go to first html page</a>
</body>
</html>